server:
  port: 9100

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_schema?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    # Redis 单机单实例
    database: 0
    host: localhost
    port: 6379
  session:
    store-type: redis

#jwt: data :这个路径是根据JWTUtil中的
#@ConfigurationProperties("jwt.data")配置的
jwt:
  data:
    #    jwt加密密钥
    secret: jfie43@5j*t4jt
    #    jwt储存的请求头Authorization固定写法
    tokenHeader: Authorization
    #      jwt的过期时间(60s*60min*24h*7day)
    expiration: 604800
    #    jwt负载中拿到的头信息
    tokenHead: Bearer


